# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c7f0cc16b5b8d2c0ea9bd2158176233"
application_url = "https://example.com"
embedded = true
name = "ai-skin-quiz"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://example.com/proxy"
prefix = "apps"
subpath = "dosha-quiz"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
