import { readFile } from 'node:fs/promises';
import { transform } from 'esbuild';
import assert from 'node:assert/strict';
let source = await readFile('app/scan.server.ts', 'utf8');
source = source.replace(/import prisma from .*?;/, 'const prisma = {};').replace(/import \{ getOpenAIKey, selectedProvider \} from .*?;/, 'const getOpenAIKey = () => null; const selectedProvider=()=>"openai";').replace(/import \{ loadQuiz, loadStoreProducts \} from .*?;/, 'const loadQuiz=()=>null; const loadStoreProducts=()=>[];');
const code = await transform(source, { loader: 'ts', format: 'esm' });
const { analysePhoto, scanResult, recommendScanProducts } = await import('data:text/javascript;base64,' + Buffer.from(code.code).toString('base64'));
const catalog = [{title:'Saffron Glow Serum',handle:'saffron-glow-serum'},{title:'Bakuchiol Night Restorative Serum',handle:'bakuchiol-night-restorative-serum'},{title:'Gift Card',handle:'gift-card'}];
assert.deepEqual(recommendScanProducts(['dullness'],[{tags:['normal_or_balanced'],productHandle:'gift-card'}],catalog).map(p=>p.handle),['saffron-glow-serum']);
assert.deepEqual(recommendScanProducts(['fine_lines'],[],catalog).map(p=>p.handle),['bakuchiol-night-restorative-serum']);
assert.equal(recommendScanProducts([],[],catalog).length,0);
let calls=0;
globalThis.fetch=async(url,options)=>{calls++; assert.equal(JSON.parse(options.body).store,false); return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({usable:true,summary:'Visible uneven tone.',concerns:[{concern:'pigmentation',observation:'Uneven tone.'}]})}]}]})};};
assert.equal((await analysePhoto('data:image/jpeg;base64,YWJj','dummy')).concerns[0].concern,'pigmentation');
await assert.rejects(()=>analysePhoto('invalid','dummy'),/Upload/);
await assert.rejects(()=>scanResult({consent:false},'test'),/Confirm/);
assert.equal(calls,1);
globalThis.fetch=async()=>({ok:false,status:401,json:async()=>({error:{code:"invalid_api_key"}})});
await assert.rejects(()=>analysePhoto('data:image/jpeg;base64,YWJj','dummy'),/invalid/);
console.log('Passed: scan recommendations, consent validation, structured response parsing and API errors. External calls mocked.');
